language: node_js
node_js:
  - "node"
before_install:
  - sudo apt update
  - sudo apt install libasound2-dev -y
install:
  - npm install --build-from-source
script:
  - npm run coveralls
deploy:
  provider: npm
  email: apexearth@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
