language: node_js
node_js:
  - "11"
  - "10"
  - "8"
before_install:
  - sudo apt update
  - sudo apt install libasound2-dev -y
script:
  - npm run coveralls
deploy:
  provider: npm
  email: apexearth@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true